vich_uploader:
    db_driver: orm

    mappings:
        image_creation_thumbnail:
            uri_prefix: /img/petites
            upload_destination: '%kernel.project_dir%/public/img/petites'

        picture:
            uri_prefix: /img/grandes
            upload_destination: '%kernel.project_dir%/public/img/grandes'