vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/creations
            upload_destination: '%kernel.project_dir%/public/images/creations'
            namer: Vich\UploaderBundle\Naming\SlugNam